# Project information
site_name: Distributed Keras
site_description: Distributed Deep Learning with Apache Spark and Keras.
site_author: Joeri Hermans
site_url: 'http://dist-keras.joerihermans.com'

# Page definitions.
pages:
- Home: index.md
- Optimizers: optimizers.md
- License: license.md
# Documentation and theme configuration
theme: readthedocs
docs_dir: 'docs'
markdown_extensions:
- admonition
extra:
    version: '0.1.0'
    palette:
        primary: 'grey'
        accent: 'light blue'
    author:
        github: 'JoeriHermans'
        twitter: 'joeri_hermans'

# Copyright
copyright: 'Copyright (c) 2016 Joeri Hermans'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/JoeriHermans/dist-keras'
